//! Release-version normalization must remove only the version label and fall back to
//! raw bytes for every manifest spelling outside its grammar.

use std::borrow::Cow;
use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

use super::{LOCKFILE, ROOT_MANIFEST, VersionNormalizer};

const MEMBER: &str = "[package]\nname = \"stickymd-core\"\nversion.workspace = true\nedition.workspace = true\n\n[dependencies]\nthiserror.workspace = true\n";
const APP: &str = "[package]\nname = \"stickymd-win\"\nversion.workspace = true\n\n[dependencies]\nstickymd-core = { path = \"../../crates/stickymd-core\", version = \"0.1.0\" }\n";

fn root_manifest(version: &str) -> String {
    format!(
        concat!(
            "[workspace]\n",
            "resolver = \"2\"\n",
            "members = [\n    \"crates/stickymd-core\",\n    \"apps/stickymd-win\", # app\n]\n\n",
            "[workspace.package]\nversion = \"{}\"\nedition = \"2024\"\n\n",
            "[workspace.dependencies]\n",
            "windows = {{ version = \"0.62.0\", default-features = false, features = [\n",
            "    \"std\",\n    \"Win32_Foundation\",\n] }}\n"
        ),
        version
    )
}

fn lockfile(version: &str) -> String {
    format!(
        concat!(
            "# This file is automatically @generated by Cargo.\n",
            "# It is not intended for manual editing.\n",
            "version = 4\n\n",
            "[[package]]\nname = \"stickymd-core\"\nversion = \"{v}\"\n",
            "dependencies = [\n \"thiserror\",\n]\n\n",
            "[[package]]\nname = \"stickymd-win\"\nversion = \"{v}\"\n",
            "dependencies = [\n \"stickymd-core\",\n]\n\n",
            "[[package]]\nname = \"thiserror\"\nversion = \"2.0.12\"\n",
            "source = \"registry+https://github.com/rust-lang/crates.io-index\"\n",
            "checksum = \"567b8a2dae586314f7be2a752ec7474332959c6460e02bde30d702a66d488708\"\n"
        ),
        v = version
    )
}

struct Fixture(PathBuf);

impl Fixture {
    fn new(root_manifest: &str, members: &[(&str, &str)]) -> Self {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let root = std::env::temp_dir().join(format!(
            "stickymd-version-normalizer-{}-{nonce}",
            std::process::id()
        ));
        fs::create_dir_all(&root).unwrap();
        fs::write(root.join(ROOT_MANIFEST), root_manifest).unwrap();
        for (path, text) in members {
            let manifest = root.join(path).join("Cargo.toml");
            fs::create_dir_all(manifest.parent().unwrap()).unwrap();
            fs::write(manifest, text).unwrap();
        }
        Self(root)
    }

    fn tracked(members: &[(&str, &str)]) -> Vec<String> {
        members
            .iter()
            .map(|(path, _)| format!("{path}/Cargo.toml"))
            .collect()
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        // Created exclusively by this test under the temp directory.
        let _ = fs::remove_dir_all(&self.0);
    }
}

const MEMBERS: [(&str, &str); 2] = [("crates/stickymd-core", MEMBER), ("apps/stickymd-win", APP)];

fn normalizer(version: &str) -> VersionNormalizer {
    let fixture = Fixture::new(&root_manifest(version), &MEMBERS);
    VersionNormalizer::read(&fixture.0, &Fixture::tracked(&MEMBERS)).expect("supported workspace")
}

fn normalized(normalizer: &VersionNormalizer, path: &str, text: &str) -> Option<String> {
    match normalizer.normalize(path, text.as_bytes()) {
        Cow::Owned(bytes) => Some(String::from_utf8(bytes).unwrap()),
        Cow::Borrowed(_) => None,
    }
}

#[test]
fn release_bump_produces_identical_normalized_manifests() {
    let old = normalizer("0.1.2");
    let new = normalizer("0.1.3");
    let old_root = normalized(&old, ROOT_MANIFEST, &root_manifest("0.1.2")).unwrap();
    let new_root = normalized(&new, ROOT_MANIFEST, &root_manifest("0.1.3")).unwrap();
    assert_eq!(old_root, new_root);
    assert!(!old_root.contains("version = \"0.1.2\""));
    assert!(old_root.contains("windows = { version = \"0.62.0\""));
    let old_lock = normalized(&old, LOCKFILE, &lockfile("0.1.2")).unwrap();
    let new_lock = normalized(&new, LOCKFILE, &lockfile("0.1.3")).unwrap();
    assert_eq!(old_lock, new_lock);
    // External package versions and checksums remain part of the fingerprint.
    assert!(old_lock.contains("version = \"2.0.12\""));
    assert!(old_lock.contains("checksum = "));
}

#[test]
fn crlf_manifests_normalize_without_touching_other_lines() {
    let normalizer = normalizer("0.1.3");
    let crlf = root_manifest("0.1.3").replace('\n', "\r\n");
    let output = normalized(&normalizer, ROOT_MANIFEST, &crlf).unwrap();
    assert_eq!(output, crlf.replace("version = \"0.1.3\"\r\n", ""));
}

#[test]
fn dependency_changes_still_change_normalized_bytes() {
    let normalizer = normalizer("0.1.3");
    let changed = lockfile("0.1.3").replace("2.0.12", "2.0.13");
    assert_ne!(
        normalized(&normalizer, LOCKFILE, &lockfile("0.1.3")),
        normalized(&normalizer, LOCKFILE, &changed)
    );
    let root = root_manifest("0.1.3").replace("0.62.0", "0.63.0");
    assert_ne!(
        normalized(&normalizer, ROOT_MANIFEST, &root_manifest("0.1.3")),
        normalized(&normalizer, ROOT_MANIFEST, &root)
    );
}

#[test]
fn unsupported_root_manifest_spellings_disable_normalization() {
    let base = root_manifest("0.1.3");
    for unsupported in [
        base.replace(
            "version = \"0.1.3\"",
            "version = \"0.1.3\"\nversion = \"0.1.4\"",
        ),
        base.replace(
            "[workspace.package]\nversion = \"0.1.3\"\n",
            "workspace.package.version = \"0.1.3\"\n[workspace.package]\n",
        ),
        base.replace(
            "[workspace.package]\nversion = \"0.1.3\"",
            "[workspace]\npackage = { version = \"0.1.3\" }\n[workspace.package]",
        ),
        base.replace(
            "edition = \"2024\"",
            "description = \"\"\"multi\nline\"\"\"",
        ),
        base.replace("version = \"0.1.3\"", "version = '0.1.3'"),
        base.replace("version = \"0.1.3\"\n", ""),
        base.replace("members = [", "members = [ \"crates/missing\","),
    ] {
        let fixture = Fixture::new(&unsupported, &MEMBERS);
        assert!(
            VersionNormalizer::read(&fixture.0, &Fixture::tracked(&MEMBERS)).is_none(),
            "{unsupported}"
        );
    }
}

#[test]
fn members_must_inherit_the_workspace_version_once() {
    for member in [
        MEMBER.replace("version.workspace = true", "version = \"0.1.3\""),
        MEMBER.replace(
            "version.workspace = true",
            "version.workspace = true\nversion.workspace = true",
        ),
        MEMBER.replace("name = \"stickymd-core\"", "name = \"stickymd-win\""),
    ] {
        let members = [("crates/stickymd-core", member.as_str()), MEMBERS[1]];
        let fixture = Fixture::new(&root_manifest("0.1.3"), &members);
        assert!(VersionNormalizer::read(&fixture.0, &Fixture::tracked(&members)).is_none());
    }
    // An untracked member manifest is not a supported workspace either.
    let fixture = Fixture::new(&root_manifest("0.1.3"), &MEMBERS);
    assert!(VersionNormalizer::read(&fixture.0, &Fixture::tracked(&MEMBERS[..1])).is_none());
}

#[test]
fn unsupported_lockfile_shapes_fall_back_to_raw_bytes() {
    let normalizer = normalizer("0.1.3");
    let base = lockfile("0.1.3");
    let duplicate_member =
        format!("{base}\n[[package]]\nname = \"stickymd-core\"\nversion = \"0.1.3\"\n");
    for unsupported in [
        // Manifest and lock disagree about the release version.
        base.replacen("version = \"0.1.3\"", "version = \"0.1.2\"", 1),
        duplicate_member,
        base.replace(
            "[[package]]\nname = \"stickymd-win\"",
            "[[package]]\nname = \"other\"",
        ),
        base.replacen(
            "dependencies = [\n \"thiserror\",",
            "source = \"registry+https://example.invalid\"\ndependencies = [\n \"thiserror\",",
            1,
        ),
        base.replace(" \"stickymd-core\",\n", " \"stickymd-core 0.1.3\",\n"),
        format!("{base}\n[metadata]\nkey = \"value\"\n"),
        base.replace("version = 4\n", "version = \"4\"\n"),
        base.replacen(
            "name = \"stickymd-core\"\n",
            "name = \"stickymd-core\"\nedition = \"2024\"\n",
            1,
        ),
        base.replace(
            "dependencies = [\n \"thiserror\",\n]\n",
            "dependencies = [\n \"thiserror\",\n",
        ),
    ] {
        assert!(
            normalized(&normalizer, LOCKFILE, &unsupported).is_none(),
            "{unsupported}"
        );
    }
    assert!(normalized(&normalizer, LOCKFILE, "\u{feff}not toml [").is_none());
}
