//! Release-version normalization must remove only the version label and fall back to
//! raw bytes for every manifest spelling outside its grammar.

use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

use super::{LOCKFILE, ROOT_MANIFEST, VersionNormalizer};

const MEMBER: &str = "[package]\nname = \"stickymd-core\"\nversion.workspace = true\nedition.workspace = true\n\n[dependencies]\nthiserror.workspace = true\n";
const APP: &str = "[package]\nname = \"stickymd-win\"\nversion.workspace = true\n\n[dependencies]\nstickymd-core = { path = \"../../crates/stickymd-core\", version = \"0.1.0\" }\n";

fn root_manifest(version: &str) -> String {
    format!(
        concat!(
            "[workspace]\n",
            "resolver = \"2\"\n",
            "members = [\n    \"crates/stickymd-core\",\n    \"apps/stickymd-win\", # app\n]\n\n",
            "[workspace.package]\nversion = \"{}\"\nedition = \"2024\"\n\n",
            "[workspace.dependencies]\n",
            "windows = {{ version = \"0.62.0\", default-features = false, features = [\n",
            "    \"std\",\n    \"Win32_Foundation\",\n] }}\n"
        ),
        version
    )
}

fn lockfile(version: &str) -> String {
    format!(
        concat!(
            "# This file is automatically @generated by Cargo.\n",
            "# It is not intended for manual editing.\n",
            "version = 4\n\n",
            "[[package]]\nname = \"stickymd-core\"\nversion = \"{v}\"\n",
            "dependencies = [\n \"thiserror\",\n]\n\n",
            "[[package]]\nname = \"stickymd-win\"\nversion = \"{v}\"\n",
            "dependencies = [\n \"stickymd-core\",\n]\n\n",
            "[[package]]\nname = \"thiserror\"\nversion = \"2.0.12\"\n",
            "source = \"registry+https://github.com/rust-lang/crates.io-index\"\n",
            "checksum = \"567b8a2dae586314f7be2a752ec7474332959c6460e02bde30d702a66d488708\"\n"
        ),
        v = version
    )
}

struct Fixture(PathBuf);

impl Fixture {
    fn new(root_manifest: &str, members: &[(&str, &str)], lock: &str) -> Self {
        static SEQUENCE: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let sequence = SEQUENCE.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let root = std::env::temp_dir().join(format!(
            "stickymd-version-normalizer-{}-{nonce}-{sequence}",
            std::process::id()
        ));
        fs::create_dir_all(&root).unwrap();
        fs::write(root.join(ROOT_MANIFEST), root_manifest).unwrap();
        fs::write(root.join(LOCKFILE), lock).unwrap();
        for (path, text) in members {
            let manifest = root.join(path).join("Cargo.toml");
            fs::create_dir_all(manifest.parent().unwrap()).unwrap();
            fs::write(manifest, text).unwrap();
        }
        Self(root)
    }

    fn tracked(members: &[(&str, &str)]) -> Vec<String> {
        members
            .iter()
            .map(|(path, _)| format!("{path}/Cargo.toml"))
            .chain([ROOT_MANIFEST.to_owned(), LOCKFILE.to_owned()])
            .collect()
    }

    fn read(&self, members: &[(&str, &str)]) -> Option<VersionNormalizer> {
        VersionNormalizer::read(&self.0, &Self::tracked(members))
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        // Created exclusively by this test under the temp directory.
        let _ = fs::remove_dir_all(&self.0);
    }
}

const MEMBERS: [(&str, &str); 2] = [("crates/stickymd-core", MEMBER), ("apps/stickymd-win", APP)];

/// A supported workspace and the normalized forms of its two manifests.
fn normalized_set(root: &str, lock: &str) -> (String, String) {
    let fixture = Fixture::new(root, &MEMBERS, lock);
    let normalizer = fixture.read(&MEMBERS).expect("supported workspace");
    let output = |path: &str, text: &str| {
        String::from_utf8(normalizer.normalize(path, text.as_bytes()).into_owned()).unwrap()
    };
    (output(ROOT_MANIFEST, root), output(LOCKFILE, lock))
}

#[test]
fn release_bump_produces_identical_normalized_manifests() {
    let old = normalized_set(&root_manifest("0.1.2"), &lockfile("0.1.2"));
    let new = normalized_set(&root_manifest("0.1.3"), &lockfile("0.1.3"));
    assert_eq!(old, new);
    assert!(!old.0.contains("version = \"0.1.2\""));
    assert!(old.0.contains("windows = { version = \"0.62.0\""));
    // External package versions and checksums remain part of the fingerprint.
    assert!(old.1.contains("version = \"2.0.12\""));
    assert!(old.1.contains("checksum = "));
    assert!(!old.1.contains("version = \"0.1.2\""));
}

#[test]
fn crlf_manifests_normalize_without_touching_other_lines() {
    let crlf = root_manifest("0.1.3").replace('\n', "\r\n");
    let (root, _) = normalized_set(&crlf, &lockfile("0.1.3"));
    assert_eq!(root, crlf.replace("version = \"0.1.3\"\r\n", ""));
}

#[test]
fn dependency_changes_still_change_normalized_bytes() {
    let base = normalized_set(&root_manifest("0.1.3"), &lockfile("0.1.3"));
    let lock = normalized_set(
        &root_manifest("0.1.3"),
        &lockfile("0.1.3").replace("2.0.12", "2.0.13"),
    );
    assert_ne!(base.1, lock.1);
    let root = normalized_set(
        &root_manifest("0.1.3").replace("0.62.0", "0.63.0"),
        &lockfile("0.1.3"),
    );
    assert_ne!(base.0, root.0);
}

#[test]
fn only_the_bytes_judged_during_planning_are_normalized() {
    let fixture = Fixture::new(&root_manifest("0.1.3"), &MEMBERS, &lockfile("0.1.3"));
    let normalizer = fixture.read(&MEMBERS).unwrap();
    // A manifest rewritten after planning is hashed raw, never as the planned form.
    let rewritten = root_manifest("0.1.4");
    assert_eq!(
        normalizer.normalize(ROOT_MANIFEST, rewritten.as_bytes()),
        rewritten.as_bytes()
    );
    let lock = lockfile("0.1.3");
    assert_ne!(
        normalizer.normalize(LOCKFILE, lock.as_bytes()),
        lock.as_bytes()
    );
    let other = b"unrelated";
    assert_eq!(normalizer.normalize("README.md", other), other.as_slice());
}

#[test]
fn unsupported_root_manifest_spellings_disable_normalization() {
    let base = root_manifest("0.1.3");
    for unsupported in [
        base.replace(
            "version = \"0.1.3\"",
            "version = \"0.1.3\"\nversion = \"0.1.4\"",
        ),
        base.replace(
            "[workspace.package]\nversion = \"0.1.3\"\n",
            "workspace.package.version = \"0.1.3\"\n[workspace.package]\n",
        ),
        base.replace(
            "[workspace.package]\nversion = \"0.1.3\"",
            "[workspace]\npackage = { version = \"0.1.3\" }\n[workspace.package]",
        ),
        base.replace(
            "edition = \"2024\"",
            "description = \"\"\"multi\nline\"\"\"",
        ),
        base.replace("version = \"0.1.3\"", "version = '0.1.3'"),
        base.replace("version = \"0.1.3\"\n", ""),
        base.replace("members = [", "members = [ \"crates/missing\","),
    ] {
        let fixture = Fixture::new(&unsupported, &MEMBERS, &lockfile("0.1.3"));
        assert!(fixture.read(&MEMBERS).is_none(), "{unsupported}");
    }
}

#[test]
fn members_must_inherit_the_workspace_version_once() {
    for member in [
        MEMBER.replace("version.workspace = true", "version = \"0.1.3\""),
        MEMBER.replace(
            "version.workspace = true",
            "version.workspace = true\nversion.workspace = true",
        ),
        MEMBER.replace("name = \"stickymd-core\"", "name = \"stickymd-win\""),
    ] {
        let members = [("crates/stickymd-core", member.as_str()), MEMBERS[1]];
        let fixture = Fixture::new(&root_manifest("0.1.3"), &members, &lockfile("0.1.3"));
        assert!(fixture.read(&members).is_none());
    }
    // Untracked member manifests or lockfiles are not a supported workspace either.
    let fixture = Fixture::new(&root_manifest("0.1.3"), &MEMBERS, &lockfile("0.1.3"));
    assert!(VersionNormalizer::read(&fixture.0, &Fixture::tracked(&MEMBERS[..1])).is_none());
    let without_lock = Fixture::tracked(&MEMBERS)
        .into_iter()
        .filter(|path| path != LOCKFILE)
        .collect::<Vec<_>>();
    assert!(VersionNormalizer::read(&fixture.0, &without_lock).is_none());
}

/// Any lockfile outside the grammar disables normalization of the whole set, including
/// the root manifest: a workspace version change then changes the fingerprint.
#[test]
fn unsupported_lockfile_shapes_keep_both_manifests_raw() {
    let base = lockfile("0.1.3");
    let duplicate_member =
        format!("{base}\n[[package]]\nname = \"stickymd-core\"\nversion = \"0.1.3\"\n");
    for unsupported in [
        // Manifest and lock disagree about the release version.
        base.replacen("version = \"0.1.3\"", "version = \"0.1.2\"", 1),
        duplicate_member,
        base.replace(
            "[[package]]\nname = \"stickymd-win\"",
            "[[package]]\nname = \"other\"",
        ),
        base.replacen(
            "dependencies = [\n \"thiserror\",",
            "source = \"registry+https://example.invalid\"\ndependencies = [\n \"thiserror\",",
            1,
        ),
        base.replace(" \"stickymd-core\",\n", " \"stickymd-core 0.1.3\",\n"),
        format!("{base}\n[metadata]\nkey = \"value\"\n"),
        base.replace("version = 4\n", "version = \"4\"\n"),
        base.replace("version = 4\n", "version = 4\nversion = 4\n"),
        base.replace("version = 4\n", ""),
        base.replace("checksum = ", "checksum = \"x\"\nchecksum = "),
        base.replace(
            "source = \"registry",
            "source = \"registry+https://example.invalid\"\nsource = \"registry",
        ),
        base.replacen(
            "dependencies = [\n \"thiserror\",\n]\n",
            "dependencies = []\ndependencies = [\n \"thiserror\",\n]\n",
            1,
        ),
        base.replacen(
            "name = \"stickymd-core\"\n",
            "name = \"stickymd-core\"\nedition = \"2024\"\n",
            1,
        ),
        base.replace(
            "dependencies = [\n \"thiserror\",\n]\n",
            "dependencies = [\n \"thiserror\",\n",
        ),
        "\u{feff}not toml [".to_owned(),
    ] {
        let fixture = Fixture::new(&root_manifest("0.1.3"), &MEMBERS, &unsupported);
        assert!(fixture.read(&MEMBERS).is_none(), "{unsupported}");
    }
}
/// Guard against manifest drift: the real workspace must stay inside the grammar,
/// otherwise every release bump silently invalidates all functional modules again.
#[test]
fn the_real_workspace_manifests_normalize() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(std::path::Path::parent)
        .expect("repository root");
    let tracked = super::super::tracked_files(root).expect("tracked files");
    let normalizer = VersionNormalizer::read(root, &tracked)
        .expect("the repository manifests must be inside the normalization grammar");
    for path in [ROOT_MANIFEST, LOCKFILE] {
        let raw = fs::read(root.join(path)).unwrap();
        assert_ne!(
            normalizer.normalize(path, &raw),
            raw.as_slice(),
            "{path} must normalize"
        );
    }
}

#[test]
fn quoted_target_tables_are_inside_the_grammar() {
    let app = format!(
        "{APP}\n[target.'cfg(windows)'.dependencies]\nwindows.workspace = true\n\n[target.\"cfg(unix)\".build-dependencies]\ncc = \"1\"\n\n[package.metadata.winresource]\nProductName = \"StickyMD\"\n"
    );
    let members = [MEMBERS[0], ("apps/stickymd-win", app.as_str())];
    let fixture = Fixture::new(&root_manifest("0.1.3"), &members, &lockfile("0.1.3"));
    assert!(fixture.read(&members).is_some());
    for broken in [
        "[target.''.dependencies]",
        "[target.'cfg(windows).dependencies]",
        "[target..dependencies]",
        "[target.'a\\b'.dependencies]",
    ] {
        let app = format!("{APP}\n{broken}\nwindows.workspace = true\n");
        let members = [MEMBERS[0], ("apps/stickymd-win", app.as_str())];
        let fixture = Fixture::new(&root_manifest("0.1.3"), &members, &lockfile("0.1.3"));
        assert!(fixture.read(&members).is_none(), "{broken}");
    }
}
